#Empilhando Tcs

library(readxl)
library(googlesheets)
library(dplyr)
library(xlsx)

lucas <- "https://drive.google.com/open?id=1g3Mf4uAg3VbUkpkm6TaqTtfAXdRosU3iV4caNrtH6lc"
gs_ls() 
lucas_sheet <- gs_title("lucas_tcs")
lucas_tcs <- lucas_sheet %>%
  gs_read() %>%
  mutate(OBS = NA)

glimpse(lucas_tcs)

liz <- "https://drive.google.com/open?id=16JegwJ_VicTTKnz5zk8RFZ9i2PM0p83Ru8EueQiD4D4"
gs_ls() 
liz_sheet <- gs_title("liz_tcs")
liz_tcs <- liz_sheet %>%
  gs_read() %>%
  mutate(OBS = NA)

jose <- "https://drive.google.com/open?id=1q49GRhtiBFYNDBBm2FrOlCqpFEZwzCP9"
gs_ls() 
jose_sheet <- gs_title("jose_tcs")
jose_tcs <- jose_sheet %>%
  gs_read()%>%
  mutate(OBS = NA)

ana <- "https://drive.google.com/open?id=1IQIeqJwgMBs_cMAU64x3wlDqFAUzrc09UxKFdAMandg"
gs_ls() 
ana_sheet <- gs_title("ana_tcs")
ana_tcs <- ana_sheet %>%
  gs_read()

#deixando todas as variáveis com as mesmas class

lucas_tcs$esfera = as.character(lucas_tcs$esfera)
lucas_tcs$poder = as.character(lucas_tcs$poder)
lucas_tcs$orgao = as.character(lucas_tcs$orgao)
lucas_tcs$protocolo = as.character(lucas_tcs$protocolo) 
lucas_tcs$assunto = as.character(lucas_tcs$assunto)
lucas_tcs$outros = as.character(lucas_tcs$outros)
lucas_tcs$atendimento = as.character(lucas_tcs$atendimento)
lucas_tcs$nao_e_pedido_de_informacao = as.character(lucas_tcs$nao_e_pedido_de_informacao)
lucas_tcs$contem_dados_pessoais = as.character(lucas_tcs$contem_dados_pessoais)
lucas_tcs$pedido = as.character(lucas_tcs$pedido)
lucas_tcs$pedido_pasta_do_anexo_pedido = as.character(lucas_tcs$pedido_pasta_do_anexo_pedido)
lucas_tcs$anexo_com_extensao_pedido = as.character(lucas_tcs$anexo_com_extensao_pedido)
lucas_tcs$resposta = as.character(lucas_tcs$resposta)
lucas_tcs$pasta_do_anexo_resposta = as.character(lucas_tcs$pasta_do_anexo_resposta)
lucas_tcs$anexo_com_extensao_resposta = as.character(lucas_tcs$anexo_com_extensao_resposta)
lucas_tcs$data_recurso_1 = as.character(lucas_tcs$data_recurso_1)
lucas_tcs$recurso_1 = as.character(lucas_tcs$recurso_1)
lucas_tcs$pasta_do_anexo_recurso_1 = as.character(lucas_tcs$pasta_do_anexo_recurso_1)
lucas_tcs$anexo_com_extensao_recurso_1 = as.character(lucas_tcs$anexo_com_extensao_recurso_1)
lucas_tcs$data_resposta_recurso_1 = as.character(lucas_tcs$data_resposta_recurso_1)
lucas_tcs$resposta_recurso_1 = as.character(lucas_tcs$resposta_recurso_1)
lucas_tcs$pasta_do_anexo_resposta_recurso_1 = as.character(lucas_tcs$pasta_do_anexo_resposta_recurso_1)
lucas_tcs$anexo_com_extensao_resposta_recurso_1 = as.character(lucas_tcs$anexo_com_extensao_resposta_recurso_1)
lucas_tcs$data_recurso_2 = as.character(lucas_tcs$data_recurso_2)
lucas_tcs$recurso_2 = as.character(lucas_tcs$recurso_2)
lucas_tcs$pasta_do_anexo_recurso_2 = as.character(lucas_tcs$pasta_do_anexo_recurso_2)
lucas_tcs$anexo_com_extensao_recurso_2 = as.character(lucas_tcs$anexo_com_extensao_recurso_2)
lucas_tcs$data_resposta_recurso_2 = as.character(lucas_tcs$data_resposta_recurso_2)
lucas_tcs$resposta_recurso_2 = as.character(lucas_tcs$resposta_recurso_2)
lucas_tcs$responsavel = as.character(lucas_tcs$responsavel)
lucas_tcs$revisado = as.character(lucas_tcs$revisado)
lucas_tcs$OBS = as.character(lucas_tcs$OBS)

#liz
liz_tcs$esfera = as.character(liz_tcs$esfera)
liz_tcs$poder = as.character(liz_tcs$poder)
liz_tcs$orgao = as.character(liz_tcs$orgao)
liz_tcs$protocolo = as.character(liz_tcs$protocolo) 
liz_tcs$assunto = as.character(liz_tcs$assunto)
liz_tcs$outros = as.character(liz_tcs$outros)
liz_tcs$atendimento = as.character(liz_tcs$atendimento)
liz_tcs$nao_e_pedido_de_informacao = as.character(liz_tcs$nao_e_pedido_de_informacao)
liz_tcs$contem_dados_pessoais = as.character(liz_tcs$contem_dados_pessoais)
liz_tcs$pedido = as.character(liz_tcs$pedido)
liz_tcs$pedido_pasta_do_anexo_pedido = as.character(liz_tcs$pedido_pasta_do_anexo_pedido)
liz_tcs$anexo_com_extensao_pedido = as.character(liz_tcs$anexo_com_extensao_pedido)
liz_tcs$resposta = as.character(liz_tcs$resposta)
liz_tcs$pasta_do_anexo_resposta = as.character(liz_tcs$pasta_do_anexo_resposta)
liz_tcs$anexo_com_extensao_resposta = as.character(liz_tcs$anexo_com_extensao_resposta)
liz_tcs$data_recurso_1 = as.character(liz_tcs$data_recurso_1)
liz_tcs$recurso_1 = as.character(liz_tcs$recurso_1)
liz_tcs$pasta_do_anexo_recurso_1 = as.character(liz_tcs$pasta_do_anexo_recurso_1)
liz_tcs$anexo_com_extensao_recurso_1 = as.character(liz_tcs$anexo_com_extensao_recurso_1)
liz_tcs$data_resposta_recurso_1 = as.character(liz_tcs$data_resposta_recurso_1)
liz_tcs$resposta_recurso_1 = as.character(liz_tcs$resposta_recurso_1)
liz_tcs$pasta_do_anexo_resposta_recurso_1 = as.character(liz_tcs$pasta_do_anexo_resposta_recurso_1)
liz_tcs$anexo_com_extensao_resposta_recurso_1 = as.character(liz_tcs$anexo_com_extensao_resposta_recurso_1)
liz_tcs$data_recurso_2 = as.character(liz_tcs$data_recurso_2)
liz_tcs$recurso_2 = as.character(liz_tcs$recurso_2)
liz_tcs$pasta_do_anexo_recurso_2 = as.character(liz_tcs$pasta_do_anexo_recurso_2)
liz_tcs$anexo_com_extensao_recurso_2 = as.character(liz_tcs$anexo_com_extensao_recurso_2)
liz_tcs$data_resposta_recurso_2 = as.character(liz_tcs$data_resposta_recurso_2)
liz_tcs$resposta_recurso_2 = as.character(liz_tcs$resposta_recurso_2)
liz_tcs$responsavel = as.character(liz_tcs$responsavel)
liz_tcs$revisado = as.character(liz_tcs$revisado)
liz_tcs$OBS = as.character(liz_tcs$OBS)

#jose
jose_tcs$esfera = as.character(jose_tcs$esfera)
jose_tcs$poder = as.character(jose_tcs$poder)
jose_tcs$orgao = as.character(jose_tcs$orgao)
jose_tcs$protocolo = as.character(jose_tcs$protocolo) 
jose_tcs$assunto = as.character(jose_tcs$assunto)
jose_tcs$outros = as.character(jose_tcs$outros)
jose_tcs$atendimento = as.character(jose_tcs$atendimento)
jose_tcs$nao_e_pedido_de_informacao = as.character(jose_tcs$nao_e_pedido_de_informacao)
jose_tcs$contem_dados_pessoais = as.character(jose_tcs$contem_dados_pessoais)
jose_tcs$pedido = as.character(jose_tcs$pedido)
jose_tcs$pedido_pasta_do_anexo_pedido = as.character(jose_tcs$pedido_pasta_do_anexo_pedido)
jose_tcs$anexo_com_extensao_pedido = as.character(jose_tcs$anexo_com_extensao_pedido)
jose_tcs$resposta = as.character(jose_tcs$resposta)
jose_tcs$pasta_do_anexo_resposta = as.character(jose_tcs$pasta_do_anexo_resposta)
jose_tcs$anexo_com_extensao_resposta = as.character(jose_tcs$anexo_com_extensao_resposta)
jose_tcs$data_recurso_1 = as.character(jose_tcs$data_recurso_1)
jose_tcs$recurso_1 = as.character(jose_tcs$recurso_1)
jose_tcs$pasta_do_anexo_recurso_1 = as.character(jose_tcs$pasta_do_anexo_recurso_1)
jose_tcs$anexo_com_extensao_recurso_1 = as.character(jose_tcs$anexo_com_extensao_recurso_1)
jose_tcs$data_resposta_recurso_1 = as.character(jose_tcs$data_resposta_recurso_1)
jose_tcs$resposta_recurso_1 = as.character(jose_tcs$resposta_recurso_1)
jose_tcs$pasta_do_anexo_resposta_recurso_1 = as.character(jose_tcs$pasta_do_anexo_resposta_recurso_1)
jose_tcs$anexo_com_extensao_resposta_recurso_1 = as.character(jose_tcs$anexo_com_extensao_resposta_recurso_1)
jose_tcs$data_recurso_2 = as.character(jose_tcs$data_recurso_2)
jose_tcs$recurso_2 = as.character(jose_tcs$recurso_2)
jose_tcs$pasta_do_anexo_recurso_2 = as.character(jose_tcs$pasta_do_anexo_recurso_2)
jose_tcs$anexo_com_extensao_recurso_2 = as.character(jose_tcs$anexo_com_extensao_recurso_2)
jose_tcs$data_resposta_recurso_2 = as.character(jose_tcs$data_resposta_recurso_2)
jose_tcs$resposta_recurso_2 = as.character(jose_tcs$resposta_recurso_2)
jose_tcs$responsavel = as.character(jose_tcs$responsavel)
jose_tcs$revisado = as.character(jose_tcs$revisado)
jose_tcs$OBS = as.character(jose_tcs$OBS)

#ana
ana_tcs$esfera = as.character(ana_tcs$esfera)
ana_tcs$poder = as.character(ana_tcs$poder)
ana_tcs$orgao = as.character(ana_tcs$orgao)
ana_tcs$protocolo = as.character(ana_tcs$protocolo) 
ana_tcs$assunto = as.character(ana_tcs$assunto)
ana_tcs$outros = as.character(ana_tcs$outros)
ana_tcs$atendimento = as.character(ana_tcs$atendimento)
ana_tcs$nao_e_pedido_de_informacao = as.character(ana_tcs$nao_e_pedido_de_informacao)
ana_tcs$contem_dados_pessoais = as.character(ana_tcs$contem_dados_pessoais)
ana_tcs$pedido = as.character(ana_tcs$pedido)
ana_tcs$pedido_pasta_do_anexo_pedido = as.character(ana_tcs$pedido_pasta_do_anexo_pedido)
ana_tcs$anexo_com_extensao_pedido = as.character(ana_tcs$anexo_com_extensao_pedido)
ana_tcs$resposta = as.character(ana_tcs$resposta)
ana_tcs$pasta_do_anexo_resposta = as.character(ana_tcs$pasta_do_anexo_resposta)
ana_tcs$anexo_com_extensao_resposta = as.character(ana_tcs$anexo_com_extensao_resposta)
ana_tcs$data_recurso_1 = as.character(ana_tcs$data_recurso_1)
ana_tcs$recurso_1 = as.character(ana_tcs$recurso_1)
ana_tcs$pasta_do_anexo_recurso_1 = as.character(ana_tcs$pasta_do_anexo_recurso_1)
ana_tcs$anexo_com_extensao_recurso_1 = as.character(ana_tcs$anexo_com_extensao_recurso_1)
ana_tcs$data_resposta_recurso_1 = as.character(ana_tcs$data_resposta_recurso_1)
ana_tcs$resposta_recurso_1 = as.character(ana_tcs$resposta_recurso_1)
ana_tcs$pasta_do_anexo_resposta_recurso_1 = as.character(ana_tcs$pasta_do_anexo_resposta_recurso_1)
ana_tcs$anexo_com_extensao_resposta_recurso_1 = as.character(ana_tcs$anexo_com_extensao_resposta_recurso_1)
ana_tcs$data_recurso_2 = as.character(ana_tcs$data_recurso_2)
ana_tcs$recurso_2 = as.character(ana_tcs$recurso_2)
ana_tcs$pasta_do_anexo_recurso_2 = as.character(ana_tcs$pasta_do_anexo_recurso_2)
ana_tcs$anexo_com_extensao_recurso_2 = as.character(ana_tcs$anexo_com_extensao_recurso_2)
ana_tcs$data_resposta_recurso_2 = as.character(ana_tcs$data_resposta_recurso_2)
ana_tcs$resposta_recurso_2 = as.character(ana_tcs$resposta_recurso_2)
ana_tcs$responsavel = as.character(ana_tcs$responsavel)
ana_tcs$revisado = as.character(ana_tcs$revisado)
ana_tcs$OBS = as.character(ana_tcs$OBS)

glimpse(ana_tcs)
glimpse(jose_tcs)
glimpse(liz_tcs)
glimpse(lucas_tcs)

tcs_classificados <- bind_rows(ana_tcs, jose_tcs, liz_tcs, lucas_tcs)

setwd("C:\\Users\\jvoig\\OneDrive\\Documentos\\colab_tb")
write.xlsx(as.data.frame(tcs_classificados), file="tcs_classificados.xlsx", sheetName="tcs_classificados",
           col.names=TRUE, row.names=FALSE, append=FALSE, showNA=FALSE)
